# Generated by Django 4.2.4 on 2023-08-21 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_address_txref_delete_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TxRef',
        ),
    ]
